#!/bin/bash

# USE Messenger - Быстрые команды для деплоя
# Выберите нужную команду и скопируйте

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║          USE Messenger - Быстрые команды деплоя            ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Цвета
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${GREEN}1. НОВЫЙ СЕРВЕР (Рекомендуется)${NC}"
echo "   Полный автоматический деплой на чистый сервер"
echo ""
echo -e "${BLUE}   cd C:/USE/deploy${NC}"
echo -e "${BLUE}   chmod +x full-deploy.sh${NC}"
echo -e "${BLUE}   ./full-deploy.sh <SERVER_IP> usecommunity.online${NC}"
echo ""
echo "   Пример:"
echo -e "${YELLOW}   ./full-deploy.sh 123.45.67.89 usecommunity.online${NC}"
echo ""
echo "   Время: 15-20 минут"
echo "   Требования: 2GB+ RAM, SSH доступ, домен"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}2. МИГРАЦИЯ С ТЕКУЩЕГО СЕРВЕРА${NC}"
echo "   Перенос данных с 144.31.69.7 на новый сервер"
echo ""
echo -e "${BLUE}   cd C:/USE/deploy${NC}"
echo -e "${BLUE}   chmod +x migrate.sh${NC}"
echo -e "${BLUE}   ./migrate.sh 144.31.69.7 <NEW_SERVER_IP> usecommunity.online${NC}"
echo ""
echo "   Пример:"
echo -e "${YELLOW}   ./migrate.sh 144.31.69.7 123.45.67.89 usecommunity.online${NC}"
echo ""
echo "   Время: 20-25 минут"
echo "   Переносит: БД, uploads, JWT_SECRET, .env"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}3. ЛОКАЛЬНАЯ СБОРКА (для серверов с <2GB RAM)${NC}"
echo "   Сборка на Windows, загрузка на сервер"
echo ""
echo "   На Windows:"
echo -e "${BLUE}   cd C:/USE${NC}"
echo -e "${BLUE}   docker build -t use-messenger:latest .${NC}"
echo -e "${BLUE}   docker save use-messenger:latest | gzip > use-messenger.tar.gz${NC}"
echo -e "${BLUE}   scp use-messenger.tar.gz root@<SERVER_IP>:/tmp/${NC}"
echo ""
echo "   На сервере:"
echo -e "${BLUE}   ssh root@<SERVER_IP>${NC}"
echo -e "${BLUE}   docker load < /tmp/use-messenger.tar.gz${NC}"
echo -e "${BLUE}   cd /opt/use-messenger${NC}"
echo -e "${BLUE}   docker-compose up -d${NC}"
echo ""
echo "   Время: 30-40 минут"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}4. ПРОВЕРКА ПОСЛЕ ДЕПЛОЯ${NC}"
echo ""
echo "   Проверка сайта:"
echo -e "${BLUE}   curl https://usecommunity.online${NC}"
echo ""
echo "   Проверка API:"
echo -e "${BLUE}   curl https://usecommunity.online/api/users${NC}"
echo ""
echo "   Проверка контейнера:"
echo -e "${BLUE}   ssh root@<SERVER_IP>${NC}"
echo -e "${BLUE}   cd /opt/use-messenger${NC}"
echo -e "${BLUE}   docker-compose ps${NC}"
echo -e "${BLUE}   docker-compose logs -f${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}5. УПРАВЛЕНИЕ НА СЕРВЕРЕ${NC}"
echo ""
echo "   Подключение:"
echo -e "${BLUE}   ssh root@<SERVER_IP>${NC}"
echo -e "${BLUE}   cd /opt/use-messenger${NC}"
echo ""
echo "   Статус:"
echo -e "${BLUE}   docker-compose ps${NC}"
echo ""
echo "   Логи:"
echo -e "${BLUE}   docker-compose logs -f${NC}"
echo ""
echo "   Перезапуск:"
echo -e "${BLUE}   docker-compose restart${NC}"
echo ""
echo "   Остановка:"
echo -e "${BLUE}   docker-compose down${NC}"
echo ""
echo "   Обновление:"
echo -e "${BLUE}   git pull origin main${NC}"
echo -e "${BLUE}   docker-compose up -d --build${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}6. BACKUP${NC}"
echo ""
echo "   Ручной backup:"
echo -e "${BLUE}   ssh root@<SERVER_IP>${NC}"
echo -e "${BLUE}   cd /opt/use-messenger${NC}"
echo -e "${BLUE}   cp data/use.db backups/use_\$(date +%Y%m%d).db${NC}"
echo -e "${BLUE}   tar -czf backups/uploads_\$(date +%Y%m%d).tar.gz uploads/${NC}"
echo ""
echo "   Автоматический backup настроен:"
echo "   - Каждый день в 3:00"
echo "   - Хранение 7 дней"
echo "   - Расположение: /opt/use-messenger/backups/"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}7. УСТРАНЕНИЕ НЕПОЛАДОК${NC}"
echo ""
echo "   Контейнер не запускается:"
echo -e "${BLUE}   docker-compose logs use-messenger${NC}"
echo -e "${BLUE}   docker-compose down${NC}"
echo -e "${BLUE}   docker-compose up -d --build${NC}"
echo ""
echo "   WebSocket не работает:"
echo -e "${BLUE}   nginx -t${NC}"
echo -e "${BLUE}   tail -f /var/log/nginx/error.log${NC}"
echo -e "${BLUE}   cat .env | grep ALLOWED_ORIGINS${NC}"
echo ""
echo "   Проверка памяти:"
echo -e "${BLUE}   free -h${NC}"
echo -e "${BLUE}   docker stats use-messenger${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}8. DNS НАСТРОЙКА${NC}"
echo ""
echo "   В панели управления доменом:"
echo "   Type: A"
echo "   Name: @"
echo "   Value: <SERVER_IP>"
echo "   TTL: 300"
echo ""
echo "   Проверка DNS:"
echo -e "${BLUE}   nslookup usecommunity.online${NC}"
echo -e "${BLUE}   dig usecommunity.online +short${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}9. ПОЛЕЗНЫЕ ССЫЛКИ${NC}"
echo ""
echo "   Документация:"
echo "   - READY_TO_DEPLOY.md - главная инструкция"
echo "   - DEPLOY_CHECKLIST.md - полный чеклист"
echo "   - DEPLOYMENT_REPORT.md - отчет о подготовке"
echo "   - DOCKER.md - Docker документация"
echo ""
echo "   GitHub:"
echo "   https://github.com/qst4cash/use-messenger"
echo ""
echo "   Домен:"
echo "   https://usecommunity.online"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${YELLOW}ВАЖНО:${NC}"
echo "- Сервер должен иметь минимум 2GB RAM"
echo "- SSH доступ должен быть настроен"
echo "- DNS должен указывать на сервер"
echo "- Порты 80, 443 должны быть открыты"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}✅ Проект готов к деплою!${NC}"
echo ""
echo "Выберите вариант деплоя (1, 2 или 3) и следуйте инструкциям."
echo ""
